PrimeFaces.locales['vi'] = {
    closeText: 'Tắt',
    prevText: 'Tháng trước',
    nextText: 'Tháng sau',
    monthNames: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10', 'T11', 'T12'],
    monthNamesShort: ['T1', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'T8', 'T9', 'T10', 'T11', 'T12'],
    dayNames: ['Chủ nhật', 'Thứ Hai', 'Thứ Ba', 'Thứ Tư', 'Thứ Năm', 'Thứ Sáu', 'Thứ Bảy'],
    dayNamesShort: ['CN', 'Hai', 'Ba', 'Tư', 'Năm', 'Sáu', 'Bảy'],
    dayNamesMin: ['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7'],
    weekHeader: 'Tuần',
    firstDay: 1,
    isRTL: false,
    showMonthAfterYear: false,
    yearSuffix: '',
    timeOnlyTitle: 'Chọn giờ',
    timeText: 'Giờ',
    hourText: 'Giờ',
    minuteText: 'Phút',
    secondText: 'Giây',
    currentText: 'Giờ hiện hành',
    ampm: false,
    month: 'Tháng',
    week: 'Tuần',
    day: 'Ngày',
    allDayText: 'Cả ngày'
};